name: Build PHP COMPLETED Workflow
on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up environment and install dependencies
        run: |
          echo "Setting up environment for language: ${{ inputs.language }}"
          echo "Setting up PHP... path initial"
          # Mostre o diretório atual
          pwd
          ls -l
          cd php || exit 1  # Certifique-se de que o diretório existe
          echo "Setting up PHP... path after cd php"
          pwd
          ls -l
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install php8.2 php8.2-cli php8.2-mbstring php8.2-dom -y
          composer install
     
      - name: Run unit tests
        run: |
          vendor/bin/phpunit ;;
          
      - name: Run SonarQube scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
   
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.language }}-build"
          path: |
            ./php/dist/*                # PHP
         
